### ISSUE TITLE
Can't create bin file with arduino

### ISSUE THREAD

**Issue by ArthusPVP** [wagiminator/CH552-Macropad-mini#2]
Hi, I want to create a bin file to upload to the ch552 but It doesn't works. Can you please give me the versions of the libraries you used for this project 😥? thx

**Comment by wagiminator** [comment]
You don't need external libraries, just make sure that the "src" folder is included.

**Comment by ArthusPVP** [comment]
Yes, I am able to create the .bin file it it doesn’t work on the macro pad and does some weird things ArthusLe 11 juil. 2024 à 09:03, Stefan Wagner ***@***.***> a écrit :﻿
You don't need external libraries, just make sure that the "src" folder is included.

**Comment by wagiminator** [comment]
Ah, OK. Did you compile with ArduinoIDE or with the makefile?

**Comment by ArthusPVP** [comment]
I compiled with Arduino IDEArthusLe 11 juil. 2024 à 09:34, Stefan Wagner ***@***.***> a écrit :﻿
Ah, OK. Did you compile with ArduinoIDE or with the makefile?

**Comment by wagiminator** [comment]
Make sure you have the correct settings especially for USB. However, I can't guarantee that this will work with every Arduino version and every version of CH55xduino. The safest way is to compile with make.

**Comment by ArthusPVP** [comment]
thx
